apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-mongo-deployment
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
   metadata:
     labels:
       app: mongo
   spec:
     containers:
     - name: mongo
       image: mongo:4.1.11
       ports:
       - containerPort: 27017
#       livenessProbe:
#         httpGet:
#           path: /
#           port: 8080
#         initialDelaySeconds: 30
#         periodSeconds: 30
#       readinessProbe:
#         httpGet:
#           path: /
#           port: 8080

